<%@ Page Title="" Language="VB" MasterPageFile="~/AdminMaster.master" AutoEventWireup="false" CodeFile="Category.aspx.vb" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div class ="container">
       <div class ="form-horizontal">
           
           <br />
           <br />
           <h2>Add Brand</h2>
           <hr />
           <div class ="form-group">
               <asp:Label ID="Label1" runat="server" CssClass ="col-md-2 control-label" Text="Brand Name"></asp:Label>
               <div class ="col-md-3">
                   <asp:TextBox ID="Brand" CssClass ="form-control" runat="server"></asp:TextBox>
                   <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="Brand" ErrorMessage="Enter Brand!!!" ForeColor="Red"></asp:RequiredFieldValidator>
               </div><br />
                &nbsp&nbsp&nbsp&nbsp<asp:Button ID="Btnadd" CssClass ="btn btn-success " runat="server" Text="ADD"/>
           </div>
           <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" 
                    DataKeyNames="CID" DataSourceID="SqlDataSource1" CellPadding="4" GridLines="None" CssClass="auto-style1" ForeColor="#333333" Width="268px" AutoGenerateEditButton="False">
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                       <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:CommandField ShowEditButton ="true" CausesValidation ="false" />
                        <asp:BoundField DataField="cat_name" HeaderText="BRAND NAME" 
                            SortExpression="cat_name" />
                    </Columns>
                       <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                       <SortedAscendingCellStyle BackColor="#E9E7E2" />
                       <SortedAscendingHeaderStyle BackColor="#506C8C" />
                       <SortedDescendingCellStyle BackColor="#FFFDF8" />
                       <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
           <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString='<%$ ConnectionStrings:fzone %>' SelectCommand="SELECT * FROM [Tblcategory]" DeleteCommand="DELETE FROM [Tblcategory] WHERE [CID] = @original_CID AND (([cat_name] = @original_cat_name) OR ([cat_name] IS NULL AND @original_cat_name IS NULL))" ConflictDetection="CompareAllValues" InsertCommand="INSERT INTO [Tblcategory] ([cat_name]) VALUES (@cat_name)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [Tblcategory] SET [cat_name] = @cat_name WHERE [CID] = @original_CID AND (([cat_name] = @original_cat_name) OR ([cat_name] IS NULL AND @original_cat_name IS NULL))">
               <DeleteParameters>
                   <asp:Parameter Name="original_CID" Type="Int32"></asp:Parameter>
                   <asp:Parameter Name="original_cat_name" Type="String"></asp:Parameter>
               </DeleteParameters>
               <InsertParameters>
                   <asp:Parameter Name="cat_name" Type="String"></asp:Parameter>
               </InsertParameters>
               <UpdateParameters>
                   <asp:Parameter Name="cat_name" Type="String"></asp:Parameter>
                   <asp:Parameter Name="original_CID" Type="Int32"></asp:Parameter>
                   <asp:Parameter Name="original_cat_name" Type="String"></asp:Parameter>
               </UpdateParameters>
           </asp:SqlDataSource>
        </div> 
     </div><br /><br /> 
</asp:Content>

