<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ProductView.aspx.vb" Inherits="ProductViwe" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
         <!-- Required meta tags -->
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <title>SpryStore E-commerce Category Bootstrap Responsive Website Template | Home :: W3layouts</title>
    <link href="Sprystore-Starter/assets/css/style-starter.css" rel="stylesheet" />

      <!-- Template CSS -->
  <link href="//fonts.googleapis.com/css?family=Oswald:300,400,500,600&display=swap" rel="stylesheet"/>
  <link href="//fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,900&display=swap" rel="stylesheet"/>
  <!-- Template CSS -->
    <script src="Sprystore-Starter/assets/js/all.js"></script>
    <script src="Sprystore-Starter/assets/js/app.js"></script>
    <%--<script src="Sprystore-Starter/assets/js/bootstrap.min.js"></script>--%>
    <script src="Sprystore-Starter/assets/js/imagezoom.js"></script>
    <script src="Sprystore-Starter/assets/js/jquery-2.1.4.min.js"></script>
    <script src="Sprystore-Starter/assets/js/jquery-3.3.1.min.js"></script>
    <script src="Sprystore-Starter/assets/js/jquery-ui.js"></script>
    <script src="Sprystore-Starter/assets/js/jquery.flexslider.js"></script>
   <script src="Sprystore-Starter/assets/js/jquery.magnific-popup.js"></script>
    <script src="Sprystore-Starter/assets/js/jquery.prettyPhoto.js"></script>
    <script src="Sprystore-Starter/assets/js/jquery.quicksand.js"></script>
    <script src="Sprystore-Starter/assets/js/minicart.js"></script>
    <script src="Sprystore-Starter/assets/js/popper.min.js"></script>
    <script src="Sprystore-Starter/assets/js/script.js"></script>
    <script src="Sprystore-Starter/assets/js/swiper.js"></script>
     <style type="text/css">
               .auto-style1 {
                   margin-left: 256px;
             margin-right: 0px;
         }
           </style>

         </head>
<body>
     <form id="form1" runat="server">
        <%--<section class="w3l-banner-slider-main inner-pagehny">--%>
  <div class="breadcrumb-infhny" style="background-color: #000000">

    <div class="top-header-content">

      <header class="tophny-header">
       
        <!--/nav-->
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid serarc-fluid">
            <a class="navbar-brand" href="#">
            <h1 style="color: #FFFFFF"> <asp:Label ID="Label1" runat="server" Text="F-" Font-Bold="True"></asp:Label><span class="lohny" style="color: #CC0000"><asp:Label ID="Label2" runat="server" Text="Z" Font-Bold="True"></asp:Label></span><asp:Label ID="Label3" runat="server" Text="ONE" Font-Bold="True"></asp:Label></h1></a>
           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            	<span class="navbar-toggler-icon fa fa-bars"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="UserHome.aspx" style="color: #FFFFFF">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="UserStore.aspx" style="color: #FFFFFF">Store</a>
                </li>
               
                <li class="nav-item">
                  <a class="nav-link" href="MyOrders.aspx" style="color: #FFFFFF">My Order</a>
                </li>
               

                <li class="nav-item">
                  <a class="nav-link" href="UserContact.aspx" style="color: #FFFFFF">Contact</a>
                </li>
                 <li class="nav-item">
                  <a class="nav-link" href="cart.aspx" style="color: #FFFFFF">Cart</a>
                </li>
              </ul>

            </div>
          </div>
        </nav>
        <!--//nav-->
      </header>
    </div> 
    </div>
<%--</section>--%>
         <a href="homen.aspx#101">hi</a>
     <div class="sub-one-left">
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="False" 
                    DataKeyNames="Itemid" DataSourceID="SqlDataSource1" CellPadding="4" GridLines="None" CssClass="auto-style1" ForeColor="#333333" Width="1200px">
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                       <AlternatingRowStyle BackColor="PaleGoldenrod" ForeColor="#284775" />
                    <Columns>
                        <asp:CommandField ShowEditButton="true" CausesValidation ="false" HeaderText="Edit Item" />
                        <asp:BoundField DataField="ItemId" HeaderText="Item Id" ReadOnly="True" SortExpression="Itemid" />
                        <asp:BoundField DataField="Itemname" HeaderText="Item Name" SortExpression="Itemname" />
                        <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
                        <asp:BoundField DataField="quantity" HeaderText="Quantity" SortExpression="quantity" />
                        <asp:TemplateField HeaderText="Image">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Eval("Image1") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Image ID="Image1" runat="server" Height="50px" ImageUrl='<%# Eval("Image1") %>' Width="50px"/>
                            </ItemTemplate>
                            <ItemStyle Height="10px" HorizontalAlign="Center" Width="10px" />
                        </asp:TemplateField>
                    </Columns>
                       <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                       <SortedAscendingCellStyle BackColor="#E9E7E2" />
                       <SortedAscendingHeaderStyle BackColor="#506C8C" />
                       <SortedDescendingCellStyle BackColor="#FFFDF8" />
                       <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:fzone %>" 
                    SelectCommand="SELECT [Itemid], [Itemname], [price], [quantity], [Image1] FROM [TblItem]"  UpdateCommand ="UPDATE [TblItem] Set [Itemname]=@Itemname, [price]=@price, [quantity]=@quantity where [Itemid]=@Itemid" DeleteCommand ="DELETE from [TblItem] where [Itemid]=@Itemid"></asp:SqlDataSource>
  </div> 
         <asp:RadioButtonList ID="CheckBoxList1" runat="server" CssClass="form-control" RepeatDirection="Horizontal">
                       <asp:ListItem>3</asp:ListItem>
                       <asp:ListItem>4</asp:ListItem>
                       <asp:ListItem>5</asp:ListItem>
                       <asp:ListItem>6</asp:ListItem>
                       <asp:ListItem>7</asp:ListItem>
                       <asp:ListItem>8</asp:ListItem>
                       <asp:ListItem>9</asp:ListItem>
                       <asp:ListItem>10</asp:ListItem>
                       <asp:ListItem>11</asp:ListItem>
                       <asp:ListItem>12</asp:ListItem>
                   </asp:RadioButtonList>
         <asp:RadioButtonList ID="RadioButtonList1" runat="server"></asp:RadioButtonList>
         </form>
  
</body>
   <section class="w3l-footer-22">
      <!-- footer-22 -->
      <div class="footer-hny py-5">
          <div class="container py-lg-5">
              
              <div class="below-section row">
                  <div class="columns col-lg-6">
                     <h3><a class="logo-footer" href="index.html">
                            F-<span class="lohny">Z</span>one</a></h3>
                  </div>
                  <div class="columns col-lg-6 text-lg-right">
                      <p>© 2020 F-ZONE. All rights reserved. Design by <a href="https://w3layouts.com/" target="_blank">
                              Future Programers</a>
                      </p>
                  </div>
                  <button onclick="topFunction()" id="movetop" title="Go to top">
                      <span class="fa fa-angle-double-up"></span>
                  </button>
              </div>
          </div>
      </div>
      <!-- //titels-5 -->
 <!-- move top -->

      <script>
          // When the user scrolls down 20px from the top of the document, show the button
          window.onscroll = function () {
              scrollFunction()
          };

          function scrollFunction() {
              if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                  document.getElementById("movetop").style.display = "block";
              } else {
                  document.getElementById("movetop").style.display = "none";
              }
          }

          // When the user clicks on the button, scroll to the top of the document
          function topFunction() {
              document.body.scrollTop = 0;
              document.documentElement.scrollTop = 0;
          }
      </script>
      <!-- /move top -->
  </section>


</html>
